spring:
  datasource:
    url: jdbc:h2:mem:camunda;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    client-id: ged-camunda-service-test

camunda:
  bpm:
    database:
      type: h2
      schema-update: true

workflow:
  notifications:
    task-created-topic: ${WORKFLOW_NOTIFICATIONS_TASK_CREATED_TOPIC:workflow-task-created}
