apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ged-camunda-service-hpa
  namespace: gedtotal-apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ged-camunda-service-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
