resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - servicemonitor.yaml
  - secret.yaml
  - ingress.yaml
images:
  - name: eurival/ged-camunda-service
    newTag: latest
