name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - 'src/**'
      - '.github/workflows/build-and-deploy.yaml'
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE_NAME: eurival/ged-camunda-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Set project version
        id: project-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push image
        run: mvn -B -ntp clean compile jib:build
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
      - name: Apply manifests
        run: kubectl apply -k infra/kubernetes
      - name: Check rollout
        run: kubectl rollout status deployment/ged-camunda-service-deployment -n gedtotal-apps
